library(dendextend)
library(igraph)

plot_dendrogram <- function(dend, method, max_height, cut_height, title, subtitle) {

  clust = cutree(dend, h=cut_height)
  num_clusts = length(unique(clust))
  dend = as.dendrogram(dend)
  dend = suppressWarnings(color_branches(dend, k = num_clusts, col = brewer.pal(num_clusts, "Dark2")))
  dend = suppressWarnings(color_labels(dend, k = num_clusts, col = brewer.pal(num_clusts, "Dark2")))
  par(cex.axis = 1, cex.main = 2, cex.sub = 1, bg = "#f7f7f7", mar = c(5, 4, 4, 1) + .1)
  # plot(dend, ylim = max_height, hang = -1, xlab = paste("number of clusters", num_clusts))
  labels(dend) = rep(NA, length(order.dendrogram(dend)))
  plot(dend,
       main = title,
       sub = subtitle,
       xlab = paste("cut height:", round(cut_height, 3), "number of clusters:", num_clusts),
       ylim = c(0, max_height),
       ylab = "Merge Height")

  abline(h=cut_height, lty = 2)
  nodes = get_nodes_xy(dend)
  sorted_nodes = nodes[order(nodes[,2]),]
  if (num_clusts == 1) {
    color = "#1B9E77"
  } else {
    color = "black"
  }
  segments(x0 = sorted_nodes[nrow(nodes), 1], y0 = sorted_nodes[nrow(nodes),2], y1 = max_height, col = color)
}

# igraph ------------------------------------------------------------------

#' make igraph
#'
#' @param mapperobject mapper object generated by mappeR
#'
#' @return an igraph object
#' @export
#' @examples
#' data = data.frame(x = sapply(1:100, function(x) cos(x)), y = sapply(1:100, function(x) sin(x)))
#'
#' projy = data$y
#'
#' cover = create_width_balanced_cover(min(projy), max(projy), 10, 25)
#'
#' mapperobj = create_1D_mapper_object(data, dist(data), data$y, cover)
#'
#' mapper_object_to_igraph(mapperobj)
mapper_to_igraph <- function(mapperobject) {
  vertices = mapperobject[[1]]
  edges = mapperobject[[2]]

  # deal with edgeless graphs
  if (length(edges$source) <= 1 & any(edges$source == "")) {
      mappergraph = graph_from_data_frame(d = data.frame(id = rownames(vertices), id = rownames(vertices)),
                                          vertices = vertices)
      mappergraph = delete_edges(mappergraph, E(mappergraph))
  } else {
    mappergraph = graph_from_data_frame(d = edges,
                                        directed = FALSE,
                                        vertices = vertices)
  }

  # don't label nodes
  mappergraph = set_vertex_attr(mappergraph, "label", value = NA)

  # set node size to square root of cluster size
  mappergraph = set_vertex_attr(mappergraph, "size", value = sqrt(vertices$cluster_size))

  # color nodes if binning
  if ("bin" %in% colnames(vertices)) {
    num_bins = max(vertices$bin)
    colfunc = colorRampPalette(c("blue", "gold", "red"), space = "Lab")
    mappergraph = set_vertex_attr(mappergraph,
                                  "color",
                                  value = sapply(vertices$bin, function(x)
                                    colfunc(num_bins)[x]))
  }

  return(mappergraph)
}
