library(dendextend)
library(igraph)

color_gradient <- function(n, alpha = 0) {
  colors <- colorRampPalette(c('blue', 'gold', 'red'), space = "Lab")(n)
  if (alpha == 0) {
    return(colors)
  } else {
    return(paste(colors, sprintf("%x", ceiling(255 * alpha)), sep = ""))
  }
}

plot_dendrogram <- function(dend, method, max_height, cut_height, title, subtitle) {

  clust = cutree(dend, h=cut_height) # find cluster assignments
  num_clusts = length(unique(clust)) # get number of clusters
  dend = as.dendrogram(dend) # enables us to color and customize dendrogram for plotting
  dend = color_branches(dend, k = num_clusts, col = brewer.pal(num_clusts, "Dark2")) # color branches by cluster (brewer wants at least 3 colors)
  par(cex.axis = 1, cex.main = 2, cex.sub = 1, bg = "#f7f7f7", mar = c(5, 4, 4, 1) + .1) # customize margins, etc
  labels(dend) = rep(NA, length(order.dendrogram(dend))) # get rid of dendrogram labels (they look ugly imo)
  plot(dend,
       main = title,
       sub = subtitle,
       xlab = paste("cut height:", round(cut_height, 3), "number of clusters:", num_clusts),
       ylim = c(0, max_height),
       ylab = "Merge Height")

  abline(h=cut_height, lty = 2) # draw cutline through dendrogram
  nodes = get_nodes_xy(dend) # get list of vertex coordinates of dendrogram
  sorted_nodes = nodes[order(nodes[,2]),] # sort vertices by y coordinate
  if (num_clusts == 1) {
    color = "#1B9E77"
  } else {
    color = "black"
  }
  segments(x0 = sorted_nodes[nrow(nodes), 1], y0 = sorted_nodes[nrow(nodes),2], y1 = max_height, col = color) # draw vertical from the top vertex of the dendrogram to the maximum pairwise distance
}

# igraph ------------------------------------------------------------------

#' make igraph
#'
#' @param mapperobject mapper object generated by mappeR
#'
#' @return an igraph object
#' @export
#' @examples
#' data = data.frame(x = sapply(1:100, function(x) cos(x)), y = sapply(1:100, function(x) sin(x)))
#'
#' projy = data$y
#'
#' cover = create_width_balanced_cover(min(projy), max(projy), 10, 25)
#'
#' mapperobj = create_1D_mapper_object(data, dist(data), data$y, cover)
#'
#' mapper_object_to_igraph(mapperobj)
mapper_to_igraph <- function(mapperobject) {
  vertices = mapperobject[[1]]
  edges = mapperobject[[2]]

  # deal with edgeless graphs
  if (length(edges$source) <= 1 & any(edges$source == "")) {
      mappergraph = graph_from_data_frame(d = data.frame(id = rownames(vertices), id = rownames(vertices)),
                                          vertices = vertices)
      mappergraph = delete_edges(mappergraph, E(mappergraph))
  } else {
    mappergraph = graph_from_data_frame(d = edges,
                                        directed = FALSE,
                                        vertices = vertices)
  }

  # don't label nodes
  mappergraph = set_vertex_attr(mappergraph, "label", value = NA)

  # set node size to square root of cluster size
  mappergraph = set_vertex_attr(mappergraph, "size", value = sqrt(vertices$cluster_size))

  # color nodes if binning
  if ("bin" %in% colnames(vertices)) {
    num_bins = max(vertices$bin)
    mappergraph = set_vertex_attr(mappergraph,
                                  "color",
                                  value = sapply(vertices$bin, function(x)
                                    color_gradient(num_bins, 0)[x]))
  }

  return(mappergraph)
}
